plugins {
    id 'dev.architectury.loom'
    id 'architectury-plugin'
}

architectury {
    minecraft = '1.21.1'
}

dependencies {
    minecraft "net.minecraft:minecraft:1.21.1"
    mappings loom.layered {
        it.mappings("net.fabricmc:yarn:1.21.1+build.3:v2")
    }
    
    modImplementation "net.fabricmc:fabric-loader:0.16.10"
    
    implementation project(':common')
}
