plugins {
    id 'dev.architectury.loom' version '1.9-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

allprojects {
    group = 'com.kulisaiji'
    version = '1.0.0'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "chameleon-${project.name}"
    }

    repositories {
        mavenCentral()
        maven { url 'https://maven.neoforged.net/releases/' }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.architectury.dev/' }
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }
    }
}

// common 模块特殊配置
project(':common') {
    apply plugin: 'com.gradleup.shadow'
    
    configurations {
        shade
        implementation.extendsFrom shade
    }

    dependencies {
        shade 'com.moandjiezana.toml:toml4j:0.7.2'
        implementation 'com.google.code.gson:gson:2.10.1'
    }

    shadowJar {
        configurations = [project.configurations.shade]
        archiveClassifier.set('')
        relocate 'com.moandjiezana.toml',
                  'com.kulisaiji.chameleon.shaded.com.moandjiezana.toml'
    }

    tasks.jar {
        dependsOn shadowJar
        enabled = false
    }
}
