pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://maven.neoforged.net/releases/' }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.quiltmc.org/repository/release/' }
    }
}

rootProject.name = 'Chameleon'
include 'common', 'neoforge'
