name: Build Mod

on:
  push:
    branches: [ main, dev, "1.21.1" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        loader: [fabric, neoforge]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false

      - name: Build ${{ matrix.loader }}
        run: ./gradlew ${{ matrix.loader }}:build --no-daemon

      - name: Upload artifacts (Fabric)
        if: ${{ matrix.loader == 'fabric' }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Artifacts
          path: fabric/build/libs/*.jar

      - name: Upload artifacts (NeoForge)
        if: ${{ matrix.loader == 'neoforge' }}
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-Artifacts
          path: neoforge/build/libs/*.jar
